/********* PowerSaveMode.m Cordova Plugin Implementation *******/

#import <Cordova/CDV.h>

@interface PowerSaveMode : CDVPlugin {
  // Member variables go here.
}

- (void)isPowerSaveMode:(CDVInvokedUrlCommand*)command;
@end

@implementation PowerSaveMode

// TODO: Implement actual logic. This is just the cordova skeleton generated by plugman
- (void)isPowerSaveMode:(CDVInvokedUrlCommand*)command
{
    CDVPluginResult* pluginResult = nil;
    NSString* echo = [command.arguments objectAtIndex:0];

    if (echo != nil && [echo length] > 0) {
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:echo];
    } else {
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR];
    }

    [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
}

@end
